# Select the proper tag: refer to https://github.com/SergioGasquez/esp-rs-container
# for more information about tags
image: sergiogasquez/esp-rs-env:esp32
tasks:
  - name: Adopt environment in the container image to gitpod user
    command: |
      ln -s /home/esp/.rustup /home/gitpod/.rustup
      mkdir /home/gitpod/.cargo
      ln -s /home/esp/.cargo/bin /home/gitpod/.cargo/bin
      ln -s /home/esp/.cargo/env /home/gitpod/.cargo/env
      ln -s /home/esp/.espressif /home/gitpod/.espressif
      ln -s /home/esp/esp-idf /home/gitpod/esp-idf
      source /home/gitpod/.cargo/env
      gp env IDF_PATH=/home/gitpod/esp-idf
      eval $(gp env -e)
vscode:
  extensions:
    - matklad.rust-analyzer
    - tamasfe.even-better-toml
    - vadimcn.vscode-lldb
    - anwar.resourcemonitor
    - yzhang.markdown-all-in-one
    - serayuzgur.crates
ports:
  - port: 9012